# Generated by Django 5.2.1 on 2026-02-04 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Автомобили и Джипове'), ('w', 'Гуми и джанти'), ('u', 'Части'), ('3', 'Бусове'), ('4', 'Камиони'), ('5', 'Мотоциклети'), ('6', 'Селскостопански'), ('7', 'Индустриални'), ('8', 'Кари'), ('9', 'Каравани'), ('a', 'Яхти и Лодки'), ('b', 'Ремаркета'), ('c', 'Велосипеди'), ('v', 'Аксесоари'), ('y', 'Купува'), ('z', 'Услуги')], default='1', max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('year_to', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('fuel', models.CharField(choices=[('benzin', 'Бензин'), ('dizel', 'Дизел'), ('gaz_benzin', 'Газ/Бензин'), ('hibrid', 'Хибрид'), ('elektro', 'Електро')], max_length=20)),
                ('gearbox', models.CharField(choices=[('ruchna', 'Ръчна'), ('avtomatik', 'Автоматик')], max_length=20)),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Listing',
                'verbose_name_plural': 'Car Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_listings/%Y/%m/%d/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.carlisting')),
            ],
            options={
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
                'ordering': ['order'],
            },
        ),
    ]
