# Generated by Django 5.2.1 on 2026-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_add_new_car_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='year_to',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
