# Generated by Django 5.2.1 on 2026-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Mark this image as the cover/main image for the listing'),
        ),
    ]
