# Generated by Django 6.0.2 on 2026-02-25 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # This branch is kept only for historical graph compatibility.
    # The real schema changes were introduced on the 0006_carimage_is_cover -> 0021 path.
    operations = []
