# Generated by Django 6.0.2 on 2026-02-25 18:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_for', models.CharField(blank=True, max_length=8)),
                ('accessory_category', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='AgriListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BoatsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_category', models.CharField(blank=True, max_length=120)),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('engine_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='BusesListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('load_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=60)),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('euro_standard', models.CharField(blank=True, max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='BuyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_for', models.CharField(blank=True, max_length=8)),
                ('buy_category', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='CaravanListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarListingPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CarsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ForkliftListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('lift_capacity_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ListingAnonymousView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Listing Anonymous View',
                'verbose_name_plural': 'Listing Anonymous Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('listing_type', models.CharField(choices=[('top', 'Top'), ('vip', 'VIP')], max_length=10)),
                ('plan', models.CharField(max_length=12)),
                ('source', models.CharField(choices=[('publish', 'Publish'), ('republish', 'Republish'), ('promote', 'Promote'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('discount_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('listing_title_snapshot', models.CharField(blank=True, max_length=200)),
                ('listing_brand_snapshot', models.CharField(blank=True, max_length=100)),
                ('listing_model_snapshot', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Listing View',
                'verbose_name_plural': 'Listing Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotoListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=60)),
                ('engine_type', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PartsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_for', models.CharField(blank=True, max_length=8)),
                ('part_category', models.CharField(blank=True, max_length=120)),
                ('part_element', models.CharField(blank=True, max_length=120)),
                ('part_year_from', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('part_year_to', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
            ],
        ),
        migrations.CreateModel(
            name='ServicesListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_for', models.CharField(blank=True, max_length=8)),
                ('service_category', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='TrailersListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_category', models.CharField(blank=True, max_length=120)),
                ('load_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('axles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TrucksListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('load_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=60)),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('euro_standard', models.CharField(blank=True, max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='WheelsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_for', models.CharField(blank=True, max_length=8)),
                ('offer_type', models.CharField(blank=True, max_length=8)),
                ('tire_brand', models.CharField(blank=True, max_length=120)),
                ('tire_width', models.CharField(blank=True, max_length=16)),
                ('tire_height', models.CharField(blank=True, max_length=16)),
                ('tire_diameter', models.CharField(blank=True, max_length=24)),
                ('tire_season', models.CharField(blank=True, max_length=32)),
                ('tire_speed_index', models.CharField(blank=True, max_length=16)),
                ('tire_load_index', models.CharField(blank=True, max_length=16)),
                ('tire_tread', models.CharField(blank=True, max_length=64)),
                ('wheel_brand', models.CharField(blank=True, max_length=120)),
                ('material', models.CharField(blank=True, max_length=60)),
                ('bolts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pcd', models.CharField(blank=True, max_length=24)),
                ('center_bore', models.CharField(blank=True, max_length=24)),
                ('offset', models.CharField(blank=True, max_length=24)),
                ('width', models.CharField(blank=True, max_length=24)),
                ('diameter', models.CharField(blank=True, max_length=24)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wheel_type', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='carimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Mark this image as the cover/main image for the listing'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='low_res',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carimage',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='renditions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='carimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='car_listings/thumbs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='is_kaparirano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='listing_type',
            field=models.CharField(choices=[('normal', 'Нормална'), ('top', 'Топ'), ('vip', 'VIP')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='top_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='top_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='top_plan',
            field=models.CharField(blank=True, choices=[('1d', '1 day'), ('7d', '7 days')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='vip_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='vip_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='vip_plan',
            field=models.CharField(blank=True, choices=[('7d', '7 days'), ('lifetime', 'Lifetime')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='main_category',
            field=models.CharField(choices=[('1', 'Автомобили и Джипове'), ('w', 'Гуми и джанти'), ('u', 'Части'), ('3', 'Бусове'), ('4', 'Камиони'), ('5', 'Мотоциклети'), ('6', 'Селскостопански'), ('7', 'Индустриални'), ('8', 'Кари'), ('9', 'Каравани'), ('a', 'Яхти и Лодки'), ('b', 'Ремаркета'), ('v', 'Аксесоари'), ('y', 'Купува'), ('z', 'Услуги')], default='1', max_length=1),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['is_active', 'is_draft', 'is_archived', 'created_at'], name='carlist_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['created_at'], name='carlist_created_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['price'], name='carlist_price_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['year_from'], name='carlist_year_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['mileage'], name='carlist_mileage_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['power'], name='carlist_power_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['fuel'], name='carlist_fuel_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['gearbox'], name='carlist_gearbox_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['condition'], name='carlist_condition_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['category'], name='carlist_category_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['location_region'], name='carlist_region_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['listing_type', 'top_expires_at'], name='carlist_top_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['listing_type', 'vip_expires_at'], name='carlist_vip_exp_idx'),
        ),
        migrations.AddField(
            model_name='accessorieslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='agrilisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agri_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='boatslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boats_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='buseslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buses_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='buylisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='caravanlisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caravan_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='carlistingpricehistory',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='carslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cars_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='forkliftlisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forklift_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='industriallisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='listinganonymousview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_viewer_entries', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='listingpurchase',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='listingpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_entries', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='listingview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motolisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moto_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='partslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parts_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='serviceslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='trailerslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trailers_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='truckslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trucks_details', to='listings.carlisting'),
        ),
        migrations.AddField(
            model_name='wheelslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wheels_details', to='listings.carlisting'),
        ),
        migrations.AddIndex(
            model_name='carlistingpricehistory',
            index=models.Index(fields=['listing', 'changed_at'], name='carlist_price_hist_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listinganonymousview',
            unique_together={('listing', 'session_key')},
        ),
        migrations.AddIndex(
            model_name='listingpurchase',
            index=models.Index(fields=['created_at'], name='lpurch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpurchase',
            index=models.Index(fields=['user', 'created_at'], name='lpurch_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpurchase',
            index=models.Index(fields=['listing_type', 'created_at'], name='lpurch_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpurchase',
            index=models.Index(fields=['source', 'created_at'], name='lpurch_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpurchase',
            index=models.Index(fields=['plan', 'created_at'], name='lpurch_plan_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingview',
            unique_together={('user', 'listing')},
        ),
    ]
