# Generated by Django 6.0.2 on 2026-02-25 18:48

from django.db import migrations


def ensure_carimage_columns(apps, schema_editor):
    """
    Some deployments have listings tables created outside migrations.
    Add only missing CarImage columns so ORM queries stop failing.
    """
    CarImage = apps.get_model("listings", "CarImage")
    connection = schema_editor.connection
    table_name = CarImage._meta.db_table

    with connection.cursor() as cursor:
        try:
            description = connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return

    existing = {col.name for col in description}
    required_fields = (
        "thumbnail",
        "original_width",
        "original_height",
        "low_res",
        "renditions",
    )

    # On SQLite, JSONField additions can trigger table remakes that fail on
    # legacy data. Add columns directly where possible.
    if connection.vendor == "sqlite":
        table_sql = schema_editor.quote_name(table_name)
        sqlite_column_sql = {
            "thumbnail": "varchar(100) NULL",
            "original_width": "integer NULL",
            "original_height": "integer NULL",
            "low_res": "bool NOT NULL DEFAULT 0",
            "renditions": "TEXT NOT NULL DEFAULT '{}'",
        }
        with connection.cursor() as cursor:
            for field_name, column_sql in sqlite_column_sql.items():
                if field_name in existing:
                    continue
                column_sql_name = schema_editor.quote_name(field_name)
                cursor.execute(
                    f"ALTER TABLE {table_sql} ADD COLUMN {column_sql_name} {column_sql}"
                )
                existing.add(field_name)
        return

    for field_name in required_fields:
        if field_name in existing:
            continue
        field = CarImage._meta.get_field(field_name)
        schema_editor.add_field(CarImage, field)
        existing.add(field.column)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_accessorieslisting_agrilisting_boatslisting_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_carimage_columns, migrations.RunPython.noop),
    ]
