# Generated by Django 5.2.1 on 2026-02-11 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_carlisting_top_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['is_active', 'is_draft', 'is_archived', 'created_at'], name='carlist_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['created_at'], name='carlist_created_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['price'], name='carlist_price_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['year_from'], name='carlist_year_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['mileage'], name='carlist_mileage_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['power'], name='carlist_power_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['fuel'], name='carlist_fuel_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['gearbox'], name='carlist_gearbox_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['condition'], name='carlist_condition_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['category'], name='carlist_category_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['location_region'], name='carlist_region_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['listing_type', 'top_expires_at'], name='carlist_top_exp_idx'),
        ),
    ]
