# Generated by Django 5.2.1 on 2026-02-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_carlisting_carlist_state_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='car_listings/thumbs/%Y/%m/%d/'),
        ),
    ]
