# Generated by Django 5.2.1 on 2026-02-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_carimage_thumbnail_carlisting_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='main_category',
            field=models.CharField(choices=[('1', 'Автомобили и Джипове'), ('w', 'Гуми и джанти'), ('u', 'Части'), ('3', 'Бусове'), ('4', 'Камиони'), ('5', 'Мотоциклети'), ('6', 'Селскостопански'), ('7', 'Индустриални'), ('8', 'Кари'), ('9', 'Каравани'), ('a', 'Яхти и Лодки'), ('b', 'Ремаркета'), ('v', 'Аксесоари'), ('y', 'Купува'), ('z', 'Услуги')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='AccessoriesListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_for', models.CharField(blank=True, max_length=8)),
                ('accessory_category', models.CharField(blank=True, max_length=160)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='AgriListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=120)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agri_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='BoatsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_category', models.CharField(blank=True, max_length=120)),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('engine_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boats_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='BusesListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('load_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=60)),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('euro_standard', models.CharField(blank=True, max_length=24)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buses_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='BuyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_for', models.CharField(blank=True, max_length=8)),
                ('buy_category', models.CharField(blank=True, max_length=160)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CaravanListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caravan_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='ForkliftListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('lift_capacity_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forklift_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=120)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='MotoListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=60)),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moto_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='PartsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_for', models.CharField(blank=True, max_length=8)),
                ('part_category', models.CharField(blank=True, max_length=120)),
                ('part_element', models.CharField(blank=True, max_length=120)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parts_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_for', models.CharField(blank=True, max_length=8)),
                ('service_category', models.CharField(blank=True, max_length=160)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='TrailersListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_category', models.CharField(blank=True, max_length=120)),
                ('load_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('axles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trailers_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='TrucksListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('load_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=60)),
                ('engine_type', models.CharField(blank=True, max_length=60)),
                ('euro_standard', models.CharField(blank=True, max_length=24)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trucks_details', to='listings.carlisting')),
            ],
        ),
        migrations.CreateModel(
            name='WheelsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_for', models.CharField(blank=True, max_length=8)),
                ('offer_type', models.CharField(blank=True, max_length=8)),
                ('wheel_brand', models.CharField(blank=True, max_length=120)),
                ('material', models.CharField(blank=True, max_length=60)),
                ('bolts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pcd', models.CharField(blank=True, max_length=24)),
                ('center_bore', models.CharField(blank=True, max_length=24)),
                ('offset', models.CharField(blank=True, max_length=24)),
                ('width', models.CharField(blank=True, max_length=24)),
                ('diameter', models.CharField(blank=True, max_length=24)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wheel_type', models.CharField(blank=True, max_length=60)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wheels_details', to='listings.carlisting')),
            ],
        ),
    ]
