# Generated by Django 5.2.1 on 2026-02-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_carslisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CarListingPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.carlisting')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['listing', 'changed_at'], name='carlist_price_hist_idx')],
            },
        ),
    ]
