# Generated by Django 5.2.1 on 2026-02-13 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_carlisting_view_count_carlistingpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='partslisting',
            name='part_year_from',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='partslisting',
            name='part_year_to',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
