# Generated by Django 5.2.1 on 2026-02-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0016_listingview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingAnonymousView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous_viewer_entries",
                        to="listings.carlisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Anonymous View",
                "verbose_name_plural": "Listing Anonymous Views",
                "ordering": ["-created_at"],
                "unique_together": {("listing", "session_key")},
            },
        ),
    ]
