# Generated by Django 5.2.1 on 2026-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listinganonymousview'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelslisting',
            name='tire_brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='wheelslisting',
            name='tire_diameter',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='wheelslisting',
            name='tire_height',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='wheelslisting',
            name='tire_load_index',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='wheelslisting',
            name='tire_season',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='wheelslisting',
            name='tire_speed_index',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='wheelslisting',
            name='tire_tread',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wheelslisting',
            name='tire_width',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
