# Generated by Django 5.2.1 on 2026-02-25 14:43

from django.db import migrations
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_carlisting_is_kaparirano'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='low_res',
            field=django.db.models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carimage',
            name='original_height',
            field=django.db.models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='original_width',
            field=django.db.models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='renditions',
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
    ]
