# Generated by Django 5.2.1 on 2026-02-25 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_carimage_renditions_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('listing_type', models.CharField(choices=[('top', 'Top'), ('vip', 'VIP')], max_length=10)),
                ('plan', models.CharField(max_length=12)),
                ('source', models.CharField(choices=[('publish', 'Publish'), ('republish', 'Republish'), ('promote', 'Promote'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('discount_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('listing_title_snapshot', models.CharField(blank=True, max_length=200)),
                ('listing_brand_snapshot', models.CharField(blank=True, max_length=100)),
                ('listing_model_snapshot', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to='listings.carlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='lpurch_created_idx'), models.Index(fields=['user', 'created_at'], name='lpurch_user_created_idx'), models.Index(fields=['listing_type', 'created_at'], name='lpurch_type_created_idx'), models.Index(fields=['source', 'created_at'], name='lpurch_source_created_idx'), models.Index(fields=['plan', 'created_at'], name='lpurch_plan_created_idx')],
            },
        ),
    ]
