# Generated by Django 6.0.2 on 2026-02-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_ensure_carimage_schema"),
        ("listings", "0021_listingpurchase"),
    ]

    operations = []
