# Generated by Django 6.0.2 on 2026-03-01 00:00

from django.db import migrations, models


def ensure_moderation_schema(apps, schema_editor):
    CarListing = apps.get_model("listings", "CarListing")
    connection = schema_editor.connection
    table_name = CarListing._meta.db_table

    with connection.cursor() as cursor:
        try:
            description = connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return

    existing_columns = {column.name for column in description}
    required_columns = ("risk_score", "risk_flags", "requires_moderation")

    if connection.vendor == "sqlite":
        table_sql = schema_editor.quote_name(table_name)
        sqlite_column_sql = {
            "risk_score": "integer NOT NULL DEFAULT 0",
            "risk_flags": "TEXT NOT NULL DEFAULT '[]'",
            "requires_moderation": "bool NOT NULL DEFAULT 0",
        }
        with connection.cursor() as cursor:
            for field_name, column_sql in sqlite_column_sql.items():
                if field_name in existing_columns:
                    continue
                column_sql_name = schema_editor.quote_name(field_name)
                cursor.execute(
                    f"ALTER TABLE {table_sql} ADD COLUMN {column_sql_name} {column_sql}"
                )
                existing_columns.add(field_name)

        with connection.cursor() as cursor:
            existing_index_names = {
                row[1]
                for row in cursor.execute(f"PRAGMA index_list('{table_name}')").fetchall()
            }
            if "carlist_mod_created_idx" not in existing_index_names:
                cursor.execute(
                    "CREATE INDEX carlist_mod_created_idx "
                    "ON listings_carlisting (requires_moderation, created_at)"
                )
        return

    for field_name in required_columns:
        if field_name in existing_columns:
            continue
        field = CarListing._meta.get_field(field_name)
        schema_editor.add_field(CarListing, field)
        existing_columns.add(field.column)

    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)
    if "carlist_mod_created_idx" not in constraints:
        schema_editor.add_index(
            CarListing,
            models.Index(
                fields=["requires_moderation", "created_at"],
                name="carlist_mod_created_idx",
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0022_merge_20260228_1"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_moderation_schema, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="carlisting",
                    name="requires_moderation",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="carlisting",
                    name="risk_flags",
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name="carlisting",
                    name="risk_score",
                    field=models.PositiveSmallIntegerField(default=0),
                ),
                migrations.AddIndex(
                    model_name="carlisting",
                    index=models.Index(
                        fields=["requires_moderation", "created_at"],
                        name="carlist_mod_created_idx",
                    ),
                ),
            ],
        ),
    ]
