# Generated by Django 5.2.1 on 2026-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_carlisting_moderation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='fuel',
            field=models.CharField(blank=True, choices=[('benzin', 'Бензин'), ('dizel', 'Дизел'), ('gaz_benzin', 'Газ/Бензин'), ('hibrid', 'Хибрид'), ('elektro', 'Електро')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='gearbox',
            field=models.CharField(blank=True, choices=[('ruchna', 'Ръчна'), ('avtomatik', 'Автоматик')], default='', max_length=20),
        ),
    ]
