# Generated by Django 6.0.2 on 2026-03-05 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_carslisting_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='BaseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('cars', 'Автомобили и Джипове'), ('wheels', 'Гуми и джанти'), ('parts', 'Части'), ('buses', 'Бусове'), ('trucks', 'Камиони'), ('motorcycles', 'Мотоциклети'), ('agriculture', 'Селскостопански'), ('industrial', 'Индустриални'), ('forklifts', 'Кари'), ('rvs', 'Каравани'), ('yachts', 'Яхти и Лодки'), ('trailer', 'Ремаркета'), ('accessories', 'Аксесоари'), ('buy', 'Купува'), ('services', 'Услуги')], default='cars', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('location_region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_kaparirano', models.BooleanField(default=False)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('requires_moderation', models.BooleanField(default=False)),
                ('listing_type', models.CharField(choices=[('normal', 'Нормална'), ('top', 'Топ'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('top_plan', models.CharField(blank=True, choices=[('1d', '1 day'), ('7d', '7 days')], max_length=12, null=True)),
                ('top_paid_at', models.DateTimeField(blank=True, null=True)),
                ('top_expires_at', models.DateTimeField(blank=True, null=True)),
                ('vip_plan', models.CharField(blank=True, choices=[('7d', '7 days'), ('lifetime', 'Lifetime')], max_length=12, null=True)),
                ('vip_paid_at', models.DateTimeField(blank=True, null=True)),
                ('vip_expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'listings_carlisting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_state_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_mileage_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_power_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_fuel_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_gearbox_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_condition_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_region_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_top_exp_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_vip_exp_idx',
        ),
        migrations.RemoveIndex(
            model_name='carlisting',
            name='carlist_mod_created_idx',
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['order'], 'verbose_name': 'Listing Image', 'verbose_name_plural': 'Listing Images'},
        ),
        migrations.RenameIndex(
            model_name='carlistingpricehistory',
            new_name='list_price_hist_idx',
            old_name='carlist_price_hist_idx',
        ),
        migrations.AddField(
            model_name='baselisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessorieslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='agrilisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agri_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='boatslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boats_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='buseslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buses_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='buylisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='caravanlisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caravan_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='carlistingpricehistory',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='carslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cars_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='forkliftlisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forklift_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='industriallisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='listinganonymousview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_viewer_entries', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='listingpurchase',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_entries', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='motolisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moto_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='partslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parts_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='serviceslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='trailerslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trailers_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='truckslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trucks_details', to='listings.baselisting'),
        ),
        migrations.AlterField(
            model_name='wheelslisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wheels_details', to='listings.baselisting'),
        ),
        migrations.AddIndex(
            model_name='carimage',
            index=models.Index(fields=['listing', 'order'], name='carimg_listing_order_idx'),
        ),
        migrations.AddIndex(
            model_name='carimage',
            index=models.Index(fields=['listing', 'is_cover'], name='carimg_listing_cover_idx'),
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='user',
        ),
        migrations.AddIndex(
            model_name='baselisting',
            index=models.Index(fields=['is_active', 'is_draft', 'is_archived', 'main_category', 'created_at'], name='listing_state_cat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='baselisting',
            index=models.Index(fields=['created_at'], name='listing_created_idx'),
        ),
        migrations.AddIndex(
            model_name='baselisting',
            index=models.Index(fields=['main_category', 'created_at'], name='listing_cat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='baselisting',
            index=models.Index(fields=['price'], name='listing_price_idx'),
        ),
        migrations.AddIndex(
            model_name='baselisting',
            index=models.Index(fields=['main_category', 'price'], name='listing_cat_price_idx'),
        ),
        migrations.AddIndex(
            model_name='baselisting',
            index=models.Index(fields=['requires_moderation', 'created_at'], name='listing_mod_created_idx'),
        ),
        migrations.AddIndex(
            model_name='baselisting',
            index=models.Index(fields=['listing_type', 'top_expires_at'], name='listing_top_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='baselisting',
            index=models.Index(fields=['listing_type', 'vip_expires_at'], name='listing_vip_exp_idx'),
        ),
            ],
            database_operations=[],
        ),
    ]
