# Generated by Django 6.0.2 on 2026-03-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_normalize_private_username_alnum'),
        ('listings', '0026_baselisting_and_more'),
        ('reports', '0004_alter_listingreport_listing'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.DeleteModel(
            name='CarListing',
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('listings.baselisting',),
        ),
            ],
            database_operations=[],
        ),
    ]
