# Generated by Django 5.2.1 on 2026-03-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_expand_listing_detail_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarListing',
        ),
    ]
