# Generated by Django 5.2.1 on 2026-03-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_rename_carlistingpricehistory_baselistingpricehistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='baselisting',
            table='listings_baselisting',
        ),
    ]
