# Generated by Django 5.2.1 on 2026-03-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_alter_baselisting_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselisting',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('CAD', 'CAD')], default='EUR', max_length=3),
        ),
    ]
