export const OUTSIDE_BULGARIA_COUNTRY_OPTIONS: Array<{ value: string; label: string }> = [
  { value: "Австрия", label: "Австрия" },
  { value: "Азербайджан", label: "Азербайджан" },
  { value: "Албания", label: "Албания" },
  { value: "Андора", label: "Андора" },
  { value: "Армения", label: "Армения" },
  { value: "Беларус", label: "Беларус" },
  { value: "Белгия", label: "Белгия" },
  { value: "Босна и Херцеговина", label: "Босна и Херцеговина" },
  { value: "Ватикан", label: "Ватикан" },
  { value: "Великобритания", label: "Великобритания" },
  { value: "Германия", label: "Германия" },
  { value: "Грузия", label: "Грузия" },
  { value: "Гърция", label: "Гърция" },
  { value: "Дания", label: "Дания" },
  { value: "Дубай", label: "Дубай" },
  { value: "Естония", label: "Естония" },
  { value: "Ирландия", label: "Ирландия" },
  { value: "Исландия", label: "Исландия" },
  { value: "Испания", label: "Испания" },
  { value: "Италия", label: "Италия" },
  { value: "Казахстан", label: "Казахстан" },
  { value: "Канада", label: "Канада" },
  { value: "Кипър", label: "Кипър" },
  { value: "Латвия", label: "Латвия" },
  { value: "Литва", label: "Литва" },
  { value: "Лихтенщайн", label: "Лихтенщайн" },
  { value: "Люксембург", label: "Люксембург" },
  { value: "Македония", label: "Македония" },
  { value: "Малта", label: "Малта" },
  { value: "Молдова", label: "Молдова" },
  { value: "Монако", label: "Монако" },
  { value: "Нидерландия", label: "Нидерландия" },
  { value: "Норвегия", label: "Норвегия" },
  { value: "Полша", label: "Полша" },
  { value: "Португалия", label: "Португалия" },
  { value: "Румъния", label: "Румъния" },
  { value: "Русия", label: "Русия" },
  { value: "Сан Марино", label: "Сан Марино" },
  { value: "САЩ", label: "САЩ" },
  { value: "Словакия", label: "Словакия" },
  { value: "Словения", label: "Словения" },
  { value: "Сърбия", label: "Сърбия" },
  { value: "Турция", label: "Турция" },
  { value: "Украйна", label: "Украйна" },
  { value: "Унгария", label: "Унгария" },
  { value: "Финландия", label: "Финландия" },
  { value: "Франция", label: "Франция" },
  { value: "Хърватия", label: "Хърватия" },
  { value: "Черна гора", label: "Черна гора" },
  { value: "Чехия", label: "Чехия" },
  { value: "Швейцария", label: "Швейцария" },
  { value: "Швеция", label: "Швеция" },
  { value: "Южна Корея", label: "Южна Корея" },
  { value: "Япония", label: "Япония" },
];
