# Generated by Django 5.2.1 on 2026-02-04 14:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('website', models.URLField(blank=True, null=True)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('company_name', models.CharField(max_length=60)),
                ('registration_address', models.CharField(max_length=80)),
                ('mol', models.CharField(max_length=35)),
                ('bulstat', models.CharField(max_length=25)),
                ('vat_number', models.CharField(blank=True, max_length=25, null=True)),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_phone', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business User',
                'verbose_name_plural': 'Business Users',
            },
        ),
        migrations.CreateModel(
            name='PrivateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private User',
                'verbose_name_plural': 'Private Users',
            },
        ),
    ]
