# Generated by Django 6.0.2 on 2026-02-25 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0006_accessorieslisting_agrilisting_boatslisting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_photos/'),
        ),
        migrations.CreateModel(
            name='UserImportApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_prefix', models.CharField(blank=True, max_length=16)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_api_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Import API Key',
                'verbose_name_plural': 'User Import API Keys',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ImportApiUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_listing_id_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('endpoint', models.CharField(default='/api/auth/import/copart/', max_length=120)),
                ('request_method', models.CharField(default='POST', max_length=12)),
                ('source', models.CharField(choices=[('extension', 'Chrome Extension'), ('public_api', 'Public API'), ('unknown', 'Unknown')], default='extension', max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_host', models.CharField(blank=True, db_index=True, max_length=255)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('extension_version', models.CharField(blank=True, max_length=32)),
                ('payload_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('imported_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_api_usage_events', to='listings.carlisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_api_usage_events', to=settings.AUTH_USER_MODEL)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='accounts.userimportapikey')),
            ],
            options={
                'verbose_name': 'Import API Usage Event',
                'verbose_name_plural': 'Import API Usage Events',
                'indexes': [models.Index(fields=['user', 'created_at'], name='impapi_usr_created_idx'), models.Index(fields=['source', 'created_at'], name='impapi_src_created_idx'), models.Index(fields=['success', 'created_at'], name='impapi_ok_created_idx'), models.Index(fields=['status_code', 'created_at'], name='impapi_st_created_idx')],
            },
        ),
    ]
