# Generated by Django 6.0.2 on 2026-02-25 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("listings", "0006_accessorieslisting_agrilisting_boatslisting_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Historical branch kept only to satisfy merge dependencies in accounts.0006.
    # Canonical schema changes are applied on the 0002_userprofile -> 0005 path.
    operations = []
