# Generated by Django 5.2.1 on 2026-02-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_photos/'),
        ),
    ]
