# Generated by Django 5.2.1 on 2026-02-18 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_import_api_key_table(apps, schema_editor):
    from backend.accounts.models import UserImportApiKey

    table_name = UserImportApiKey._meta.db_table
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name in existing_tables:
        return
    schema_editor.create_model(UserImportApiKey)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businessuser_about_text_businessuser_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_user_import_api_key_table,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='UserImportApiKey',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('key_prefix', models.CharField(blank=True, max_length=16)),
                        ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                        ('last_used_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_api_key', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'User Import API Key',
                        'verbose_name_plural': 'User Import API Keys',
                    },
                ),
            ],
        ),
    ]
