# Generated by Django 6.0.2 on 2026-02-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_businessuser_about_text_businessuser_profile_image_and_more"),
        ("accounts", "0005_importapiusageevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessuser",
            name="dealer_name",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
