# Generated by Django 6.0.2 on 2026-02-28 16:35

import re
import unicodedata
from django.db import migrations, models


def _slugify_username(value: str) -> str:
    normalized = unicodedata.normalize("NFKC", str(value or "")).strip().lower()
    cleaned = re.sub(r"[^a-z0-9._-]+", "-", normalized)
    cleaned = re.sub(r"-{2,}", "-", cleaned).strip("-")
    return cleaned or "user"


def populate_private_usernames(apps, schema_editor):
    PrivateUser = apps.get_model("accounts", "PrivateUser")
    used = set()

    for profile in PrivateUser.objects.select_related("user").order_by("id"):
        base_from_email = _slugify_username((profile.email or "").split("@", 1)[0])
        candidate = base_from_email

        if (
            not candidate
            or candidate in used
            or PrivateUser.objects.exclude(id=profile.id).filter(username__iexact=candidate).exists()
        ):
            candidate = f"user-{profile.user_id or profile.id}"

        suffix = 1
        unique_candidate = candidate
        while (
            unique_candidate in used
            or PrivateUser.objects.exclude(id=profile.id).filter(username__iexact=unique_candidate).exists()
        ):
            suffix += 1
            unique_candidate = f"{candidate}-{suffix}"

        profile.username = unique_candidate[:32]
        profile.save(update_fields=["username"])
        used.add(profile.username.lower())


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_businessuser_dealer_name_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="privateuser",
            name="username",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(populate_private_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="privateuser",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
