# Generated by Django 6.0.2 on 2026-02-28 16:50

import re
from django.db import migrations


def _normalize_username(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "", str(value or "").strip().lower())
    return normalized[:32]


def normalize_private_usernames(apps, schema_editor):
    PrivateUser = apps.get_model("accounts", "PrivateUser")
    used = set()

    for profile in PrivateUser.objects.select_related("user").order_by("id"):
        candidate = _normalize_username(profile.username)
        if len(candidate) < 3:
            candidate = f"user{profile.user_id or profile.id}"

        base_candidate = candidate
        suffix = 1
        while (
            candidate in used
            or PrivateUser.objects.exclude(id=profile.id).filter(username__iexact=candidate).exists()
        ):
            suffix += 1
            raw = f"{base_candidate}{suffix}"
            candidate = raw[:32]
            if len(candidate) < 3:
                candidate = f"user{profile.id}{suffix}"[:32]

        profile.username = candidate
        profile.save(update_fields=["username"])
        used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_privateuser_username"),
    ]

    operations = [
        migrations.RunPython(normalize_private_usernames, migrations.RunPython.noop),
    ]
