# Generated by Django 5.2.1 on 2026-03-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_normalize_private_username_alnum'),
        ('listings', '0031_delete_carlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importapiusageevent',
            name='imported_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_api_usage_events', to='listings.baselisting'),
        ),
    ]
