# Generated by Django 5.2.1 on 2026-02-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0013_partslisting_part_year_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_price', models.BooleanField(default=False)),
                ('other_issue', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.carlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='listingreport',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='reports_unique_user_listing_report'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['listing', 'created_at'], name='reports_listing_created_idx'),
        ),
    ]
