# Generated by Django 5.2.1 on 2026-02-28 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("topic", models.CharField(blank=True, default="", max_length=120)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("replied", "Replied")],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                ("admin_reply", models.TextField(blank=True, default="")),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_inquiry_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contactinquiry",
            index=models.Index(fields=["status", "created_at"], name="reports_contact_status_idx"),
        ),
        migrations.AddIndex(
            model_name="contactinquiry",
            index=models.Index(fields=["email", "created_at"], name="reports_contact_email_idx"),
        ),
    ]
