# Generated by Django 5.2.1 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_contactinquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="customer_replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="customer_reply",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="last_inbound_message_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
