# Generated by Django 6.0.2 on 2026-03-05 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_baselisting_and_more'),
        ('reports', '0003_contactinquiry_customer_reply_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.AlterField(
            model_name='listingreport',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.baselisting'),
        ),
            ],
            database_operations=[],
        ),
    ]
